// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jsonpath.proxies;

public enum BooleanValue
{
	_true("db71b171-35bb-481a-a380-5125fc194ea5"),
	_false("0f1ca3f4-7885-4a8c-a822-273597008dc9");

	private final java.lang.String i18nCaptionKey;
	
	private BooleanValue(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
