// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonpath.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetDecimalFromJSONByPath extends CustomJavaAction<java.math.BigDecimal>
{
	private java.lang.String json;
	private java.lang.String path;

	public GetDecimalFromJSONByPath(IContext context, java.lang.String json, java.lang.String path)
	{
		super(context);
		this.json = json;
		this.path = path;
	}

	@Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		final Number numberValue = JSONUtils.getValueFromJSONStringByPath(json, path, Number.class);
		return (numberValue != null) ? java.math.BigDecimal.valueOf(numberValue.doubleValue()) : null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetDecimalFromJSONByPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
