// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonpath.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * GetIntegerFromJSONByPath
 * * Returns first Integer value from a JSON input matching JSONPath expression
 * * Returns empty if not found or result is not Integer/Long
 */
public class GetIntegerFromJSONByPath extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String json;
	private java.lang.String path;

	public GetIntegerFromJSONByPath(IContext context, java.lang.String json, java.lang.String path)
	{
		super(context);
		this.json = json;
		this.path = path;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Number numberValue = JSONUtils.getValueFromJSONStringByPath(json, path, Number.class);
		if (Integer.class.isInstance(numberValue) || Long.class.isInstance(numberValue)) {
			return numberValue.longValue();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetIntegerFromJSONByPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
