// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonpath.actions;

import java.util.LinkedHashMap;
import org.json.simple.JSONObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetJSONObjectFromJSONByPath extends CustomJavaAction<java.lang.String>
{
	private java.lang.String json;
	private java.lang.String path;

	public GetJSONObjectFromJSONByPath(IContext context, java.lang.String json, java.lang.String path)
	{
		super(context);
		this.json = json;
		this.path = path;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		@SuppressWarnings("unchecked")
		final LinkedHashMap<Object, Object> linkedHashMap = JSONUtils.getValueFromJSONStringByPath(json, path, LinkedHashMap.class);
		return (linkedHashMap != null) ? JSONObject.toJSONString(linkedHashMap) : null;		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetJSONObjectFromJSONByPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
