// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonpath.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import jsonpath.implementation.Utils;

/**
 * GetDecimalFromJSONByPath
 * * Returns first Decimal value from a JSON input matching JSONPath expression
 * * Returns empty if not found or result is not numeric (Integer, Decimal, etc.)
 */
public class GetDecimalFromJSONByPath extends CustomJavaAction<java.math.BigDecimal>
{
	private java.lang.String json;
	private java.lang.String path;

	public GetDecimalFromJSONByPath(IContext context, java.lang.String json, java.lang.String path)
	{
		super(context);
		this.json = json;
		this.path = path;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Utils.queryJSONStringForDecimal(json, path);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetDecimalFromJSONByPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
