// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsonpath.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import jsonpath.implementation.Utils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * GetIntegerFromJSONByPath
 * * Returns first Integer value from a JSON input matching JSONPath expression
 * * Returns empty if not found or result is not Integer/Long
 */
public class GetIntegerFromJSONByPath extends UserAction<java.lang.Long>
{
	private final java.lang.String json;
	private final java.lang.String path;

	public GetIntegerFromJSONByPath(
		IContext context,
		java.lang.String _json,
		java.lang.String _path
	)
	{
		super(context);
		this.json = _json;
		this.path = _path;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Number numberValue = Utils.queryJSONStringForInteger(json, path);
		if (Integer.class.isInstance(numberValue) || Long.class.isInstance(numberValue)) {
			return numberValue.longValue();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetIntegerFromJSONByPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
